apps/adopcion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
    url(r'^index$', index_adopcion),
    url(r'^solicitud/listar$', login_required(SolicitudList.as_view()), name='solicitud_listar'),
    url(r'^solicitud/nueva$', login_required(SolicitudCreate.as_view()), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>\d+)$', login_required(SolicitudUpdate.as_view()), name='solicitud_modificar'),
    url(r'^solicitud/eliminar/(?P<pk>\d+)$', login_required(SolicitudDelete.as_view()), name='solicitud_eliminar'),
]

proyectoTutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login , {'template_name':'index.html'}, name="login"),
    url(r'^logout/', logout_then_login , name="logout"),
]

apps/adopcion/models.py
from django.db import models

# Create your models here.
class Persona(models.Model):
	##id_manual = models.CharField(max_length=10,primary_key=True) <- sólo si quiero asignar de forma manual el id
	nombre = models.CharField(max_length=50)
	apellido = models.CharField(max_length=50)
	edad = models.IntegerField()
	telefono = models.CharField(max_length=50)
	email = models.EmailField()
	direccion = models.TextField()

	def __str__(self):
		return '{} {}'.format(self.nombre, self.apellido)

class Solicitud(models.Model):
	persona = models.ForeignKey(Persona, null=True, blank=True)
	numero_mascotas = models.IntegerField()
	razones = models.TextField()

apps/adopcion/forms.py
from django import forms

from apps.adopcion.models import Persona, Solicitud

class PersonaForm(forms.ModelForm):
	class Meta:
		model = Persona
		fields=[
			'nombre',
			'apellido',
			'edad',
			'telefono',
			'email',
			'direccion',
		]
		labels={
			'nombre':'Nombre',
			'apellido':'Apellido',
			'edad':'Edad',
			'telefono':'Telefono (+569 )',
			'email':'Email',
			'direccion':'Direccion',
		}
		widgets={
			'nombre':forms.TextInput(attrs={'class':'form-control'}),
			'apellido':forms.TextInput(attrs={'class':'form-control'}),
			'edad':forms.TextInput(attrs={'class':'form-control'}),
			'telefono':forms.TextInput(attrs={'class':'form-control'}),
			'email':forms.TextInput(attrs={'class':'form-control'}),
			'direccion':forms.TextInput(attrs={'class':'form-control'}),
		}

class SolicitudForm(forms.ModelForm):
	class Meta:
		model = Solicitud
		fields=[
			'numero_mascotas',
			'razones',
		]
		labels={
			'numero_mascotas':'Numero de mascotas',
			'razones':'Razones para adoptar'
		}
		widgets={
			'numero_mascotas':forms.TextInput(attrs={'class':'form-control'}),
			'razones':forms.Textarea(attrs={'class':'form-control'}),
		}

apps/adopcion/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.adopcion.models import Solicitud, Persona
from apps.adopcion.forms import SolicitudForm, PersonaForm

# Create your views here.
def index_adopcion(request):
	return HttpResponse("Index desde adopción.")

class SolicitudList(ListView):
	model = Solicitud
	template_name = 'adopcion/solicitud_list.html'

class SolicitudCreate(CreateView):
	model = Solicitud
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')

	def get_context_data(self, **kwargs):
		context = super(SolicitudCreate,self).get_context_data(**kwargs)
		if 'form' not in context:
			context['form'] = self.form_class(self.request.GET)
		if 'form2' not in context:
			context['form2'] = self.second_form_class(self.request.GET)
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		form2 = self.second_form_class(request.POST)
		if form.is_valid() and form2.is_valid():
			solicitud = form.save(commit =False)
			solicitud.persona = form2.save()
			solicitud.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return self.render_to_response(self.get_context_data(form=form, form2 =form2))

class SolicitudUpdate(UpdateView):
	model = Solicitud
	second_model = Persona
	template_name = 'adopcion/solicitud_form.html'
	form_class = SolicitudForm
	second_form_class = PersonaForm
	success_url = reverse_lazy('adopcion:solicitud_listar')

	def get_context_data(self, **kwargs):
		context = super(SolicitudUpdate,self).get_context_data(**kwargs)
		pk = self.kwargs.get('pk',0)
		solicitud = self.model.objects.get(id=pk)
		persona = self.second_model.objects.get(id=solicitud.persona_id)
		if 'form' not in context:
			context['form'] = self.form_class()
		if 'form2' not in context:
			context['form2'] = self.second_form_class(instance=persona)
		context['id']=pk
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		id_solicitud = kwargs['pk']
		solicitud = self.model.objects.get(id=id_solicitud)
		persona = self.second_model.objects.get(id= solicitud.persona_id)
		form = self.form_class(request.POST, instance=solicitud)
		form2 = self.second_form_class(request.POST, instance = persona)
		if form.is_valid() and form2.is_valid():
			form.save()
			form2.save()
			return HttpResponseRedirect(self.get_success_url())
		else:
			return self.render_to_response(self.get_context_data(form=form, form2 =form2))

class SolicitudDelete(DeleteView):
	model = Solicitud
	template_name = 'adopcion/solicitud_delete.html'
	success_url = reverse_lazy("adopcion:solicitud_listar")

templates/adopcion/solicitud_delete.html
{% extends "base/base.html" %}

{% block tittle %}
	Solicitud
{% endblock %}
{% block titulo %}
	<h5>Eliminar Solicitud</h5>
{% endblock titulo %}
{% block content %}
	<div class="row">
		<div class="col s6 offset-s3">
			<h3>¿Desea eliminar el registro de solicitud de {{object.persona.nombre}} {{object.persona.apellido}}?</h3>
			<form method="POST" style="text-align: center;">
				{% csrf_token %}
				<button class="btn waves-effect waves-light" type="submint">Sí, eliminar</button>
				<a class="btn waves-effect waves-light" href="{% url 'adopcion:solicitud_listar' %}">Cancelar</a>
			</form>	
		</div>
	</div>
{% endblock %}
{% block jsFiles %}
	<script type="text/javascript" src="{{STATIC_URL}}/static/js/mascotaform.js"></script>
{% endblock %}

templates/adopcion/solicitud_form.html
{% extends "base/base.html" %}

{% block tittle %}
	Solicitud
{% endblock %}
{% block titulo %}
	Nueva Solicitud
{% endblock titulo %}
{% block content %}
	<div class="row">
		<div class="col s8 offset-s2">
			<form method="post">
				{% csrf_token %}
				<div class=" col s6">
					<h5>Nueva Persona: </h5>
					<div class="form-group">
						<label for="{{form2.nombre.name}}">{{form2.nombre.label}}</label>
						{{form2.nombre}}
					</div>
					<div class="form-group">
						<label for="{{form2.nombre.apellidos}}">{{form2.apellido.label}}</label>
						{{form2.apellido}}
					</div>
					<div class="form-group">
						<label for="{{form2.edad.name}}">{{form2.edad.label}}</label>
						{{form2.edad}}
					</div>
					<div class="form-group">
						<label for="{{form2.telefono.name}}">{{form2.telefono.label}}</label>
						{{form2.telefono}}
					</div>
					<div class="form-group">
						<label for="{{form2.email.name}}">{{form2.email.label}}</label>
						{{form2.email}}
					</div>
					<div class="form-group">
						<label for="{{form2.direccion.name}}">{{form2.direccion.label}}</label>
						{{form2.direccion}}
					</div>
				</div>
				<div class=" col s6">
					<h5>Nueva Solicitud: </h5>
					<div class="form-group">
						<label for="{{form.numero_mascotas.name}}">{{form.numero_mascotas.label}}</label>
						{{form.numero_mascotas}}
					</div>
					<div class="form-group">
						<label for="{{form.razones.name}}">{{form.razones.label}}</label>
						{{form.razones}}
					</div>
				</div>
				<div class=" col s4 offset-s4">
					<button class="btn waves-effect waves-light" type="submint">Guardar</button>
					<button class="btn waves-effect waves-light" type="reset" >Limpiar</button>
				</div>
				{{ form.errors }}
			</form>
		</div>
	</div>
{% endblock content %}

templates/adopcion/solicitud_list.html
{% extends "base/base.html" %}
{% block tittle %}
	Solicitud
{% endblock %}
{% block titulo %}
	<h5>Lista de Solicitudes</h5>
{% endblock titulo %}
{% block content %}
	<div class="row">
		<div class="col s8 offset-s2"> 
		  	<table class="bordered">
				<thead>
					<tr>
						<td>N° de Solicitud</td>
						<td>Adoptante</td>
						<td>N° Mascota</td>
						<td>Razones</td>
						<td>Acciones</td>
					</tr>
				</thead>
				<tbody>
					{% if object_list %}
						{% for solicitud in object_list %}
							<tr>
								<td>{{solicitud.id}}</td>
								<td>{{solicitud.persona.nombre}}</td>
								<td>{{solicitud.numero_mascota}}</td>
								<td>{{solicitud.razones}}</td>
								<td>
									<a href="{% url 'adopcion:solicitud_modificar' solicitud.id %}" class="btn-floating waves-effect waves-light">
									<i class="material-icons left">mode_edit</i></a>
									<a href="{% url 'adopcion:solicitud_eliminar' solicitud.id %}" class="btn-floating waves-effect waves-light"><i class="material-icons left">delete</i></a>
								</td>
							</tr>
						{% endfor %}
					{% else %}
						<h4>No se han realizado Solicitudes aun</h4>
					{% endif %}
				</tbody>
			</table>
		</div>
  	</div>
{% endblock %}