apps/adopcion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.adopcion.views import index_adopcion, SolicitudList, SolicitudCreate, SolicitudUpdate, SolicitudDelete

urlpatterns = [
    url(r'^index$', index_adopcion),
    url(r'^solicitud/listar$', login_required(SolicitudList.as_view()), name='solicitud_listar'),
    url(r'^solicitud/nueva$', login_required(SolicitudCreate.as_view()), name='solicitud_crear'),
    url(r'^solicitud/editar/(?P<pk>\d+)$', login_required(SolicitudUpdate.as_view()), name='solicitud_modificar'),
    url(r'^solicitud/eliminar/(?P<pk>\d+)$', login_required(SolicitudDelete.as_view()), name='solicitud_eliminar'),
]

apps/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
	MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required( MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar$', login_required( MascotaList.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required( MascotaUpdate.as_view() ), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required( MascotaDelete.as_view()) , name='mascota_eliminar'),
]

proyectoTutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login , {'template_name':'index.html'}, name="login"),
    url(r'^logout/', logout_then_login , name="logout"),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
	<head>
		<meta charset="utf-8">
		<title>
			{% block tittle %}
				Document
			{% endblock %}
		</title>
		{% block cssFiles %}
		{% endblock %}
		<!--Import Google Icon Font-->
      	<link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      	<!--Import css from materialize-->
		<link rel="stylesheet" type="text/css" href="{% static "css/materialize.min.css" %}">
		<style type="text/css">
			body {display: flex;min-height: 100vh;flex-direction: column;}
			main {flex: 1 0 auto;}
		</style>
	</head>
	<body>
	{% block header %}
		{% include "base/header.html" %}
	{% endblock %}
	<div class="row">
		<div class="col s12">
			{% block titulo %}
			{% endblock titulo %}
		</div>
	</div>
	<main>
		{% block content %}
		{% endblock  %}
	</main>
	{% block footer %}
		{% include "base/footer.html" %}
	{% endblock  %}
	<!--Import js from JQuery -->
	<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	<!--Import js from materilize -->
	<script type="text/javascript" src="{% static "js/materialize.min.js" %}"></script>
	<script type="text/javascript" src="{% static "js/materialize.js" %}"></script>
	<script type="text/javascript" src="{% static "js/header.js" %}"></script>
	{% block jsFiles %}
	{% endblock %}
	</body>
</html>

templates/base/footer.html
<footer class="teal lighten-2">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text"></h5>
        <p class="grey-text text-lighten-4"></p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Twitter</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Google+</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <h6 class="white-text">© 2016 Copyright Text, All rights reserved. </h6>
    </div>
  </div>
</footer>

templates/base/header.html
<header>
	<ul id="mascota_option" class="dropdown-content">
    	<li><a href="{% url 'mascota:mascota_listar' %}">Listar<i class="Small material-icons right">view_list</i></a></li>
    	<li class="divider"></li>
    	<li><a href="{% url 'mascota:mascota_crear' %}">Nuevo<i class="Small material-icons right">playlist_add</i></a></li>
	  	<li class="divider"></li>
	  	<li><a href="#!">Modificar<i class="Small material-icons right">mode_edit</i></a></li>
	  	<li class="divider"></li>
	  	<li><a href="#!">Eliminar<i class="Small material-icons right">delete</i></a></li>
	</ul>
	<ul id="adopcion_option" class="dropdown-content">
		<li><a href="#!">Listar<i class="Small material-icons right">view_list</i></a></li>
		<li class="divider"></li>
		<li><a href="#!">Nuevo<i class="Small material-icons right">playlist_add</i></a></li>
	  	<li class="divider"></li>
	  	<li><a href="#!">Modificar<i class="Small material-icons right">mode_edit</i></a></li>
	  	<li class="divider"></li>
	  	<li><a href="#!">Eliminar<i class="Small material-icons right">delete</i></a></li>
	</ul>
	<ul id="solicitud_option" class="dropdown-content">
		<li><a href="{% url 'adopcion:solicitud_listar' %}">Listar<i class="Small material-icons right">view_list</i></a></li>
		<li class="divider"></li>
	  	<li><a href="{% url 'adopcion:solicitud_crear' %}">Nuevo<i class="Small material-icons right">playlist_add</i></a></li>
	  	<li class="divider"></li>
	  	<li><a href="#!">Modificar<i class="Small material-icons right">mode_edit</i></a></li>
	  	<li class="divider"></li>
	  	<li><a href="#!">Eliminar<i class="Small material-icons right">delete</i></a></li>
	</ul>
	<nav class="teal lighten-2">
	    <div class="nav-wrapper">
      		<a href="#" class="brand-logo"><i class="material-icons">store</i>Logo</a>
      		<a href="#" data-activates="mobile-demo" class="button-collapse right"><i class="material-icons">menu</i></a>
      		<ul class="right hide-on-med-and-down">
	        	<li><a href="{% url 'mascota:index' %}">Inicio</a></li>
		        <li><a class="dropdown-button" href="#!" data-activates="adopcion_option">Adopción<i class="material-icons right">arrow_drop_down</i></a></li>
		        <li><a class="dropdown-button" href="#!" data-activates="solicitud_option">Solicitud<i class="material-icons right">arrow_drop_down</i></a></li>
		        <li><a class="dropdown-button" href="#!" data-activates="mascota_option">Mascotas<i class="material-icons right">arrow_drop_down</i></a></li>
		        <li><a href="{% url 'logout' %}">Salir</a></li>
	      	</ul>
	      	<ul class="side-nav" id="mobile-demo">
	      		<li><a href="{% url 'mascota:index' %}">Inicio</a></li>
	      		<li><a class="dropdown-button" href="#!" data-activates="dropdown1">Adopción<i class="material-icons right">arrow_drop_down</i></a></li>
		      	<ul id='dropdown1' class='dropdown-content'>
			        <li><a href="#!">Listar<i class="Small material-icons right">view_list</i></a></li>
			        <li><a href="#!">Nuevo<i class="Small material-icons right">playlist_add</i></a></li>
			        <li><a href="#!">Modificar<i class="Small material-icons right">mode_edit</i></a></li>
			        <li><a href="#!">Eliminar</a></li>
			    </ul>
			    <li><a class="dropdown-button" href="#!" data-activates="dropdown2">Solicitud<i class="material-icons right">arrow_drop_down</i></a></li>
		      	<ul id='dropdown2' class='dropdown-content'>
			        <li><a href="{% url 'adopcion:solicitud_listar' %}">Listar<i class="Small material-icons right">view_list</i></a></li>
			        <li><a href="{% url 'adopcion:solicitud_crear' %}">Nuevo<i class="Small material-icons right">playlist_add</i></a></li>
			        <li><a href="#!">Modificar<i class="Small material-icons right">mode_edit</i></a></li>
			        <li><a href="#!">Eliminar</a></li>
			    </ul>
			    <li><a class="dropdown-button" href="#!" data-activates="dropdown3">Mascotas<i class="material-icons right">arrow_drop_down</i></a></li>
		      	<ul id='dropdown3' class='dropdown-content'>
			        <li><a href="{% url 'mascota:mascota_listar' %}">Listar<i class="Small material-icons right">view_list</i></a></li>
			        <li><a href="{% url 'mascota:mascota_crear' %}">Nuevo<i class="Small material-icons right">playlist_add</i></a></li>
			        <li><a href="#!">Modificar<i class="Small material-icons right">mode_edit</i></a></li>
			        <li><a href="#!">Eliminar</a></li>
			    </ul>
			    <li><a href="{% url 'logout' %}">Salir</a></li>
	      	</ul>
	    </div>
  	</nav>
</header>