apps/mascota/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from apps.mascota.views import index, mascota_view, mascota_list, mascota_edit, mascota_delete, \
	MascotaList, MascotaCreate, MascotaUpdate, MascotaDelete

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nuevo$', login_required( MascotaCreate.as_view()), name='mascota_crear'),
    url(r'^listar$', login_required( MascotaList.as_view()), name='mascota_listar'),
    url(r'^editar/(?P<pk>\d+)/$', login_required( MascotaUpdate.as_view() ), name='mascota_editar'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required( MascotaDelete.as_view()) , name='mascota_eliminar'),
]

proyectoTutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mascota/', include('apps.mascota.urls', namespace="mascota")),
    url(r'^adopcion/', include('apps.adopcion.urls', namespace="adopcion")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^accounts/login/', login , {'template_name':'index.html'}, name="login"),
    url(r'^logout/', logout_then_login , name="logout"),
]

apps/mascota/models.py
from django.db import models
from apps.adopcion.models import Persona

# Create your models here.
class Vacuna(models.Model):
	nombre = models.CharField(max_length=50)
	##def __str__(self): para python 3.7
	def __str__(self):
		return '{}'.format(self.nombre)

class Mascota(models.Model):
	nombre = models.CharField(max_length=50)
	sexo = models.CharField(max_length=10)
	edad_aproximada = models.IntegerField()
	fecha_rescate = models.DateField()
	persona = models.ForeignKey(Persona, null=True, blank=True, on_delete=models.CASCADE)
	vacuna = models.ManyToManyField(Vacuna, blank=True)

apps/mascota/forms.py
from django import forms
from apps.mascota.models import Mascota

class MascotaForm(forms.ModelForm):
	class Meta:
		model = Mascota

		fields=[
			'nombre',
			'edad_aproximada',
			'fecha_rescate',
			'sexo',
			'persona',
			'vacuna',
		]
		labels={
			'nombre':'Nombre',
			'edad_aproximada': 'Edad Aproximada',
			'fecha_rescate': 'Fecha de Rescate (Ejemplo: AAAA-MM-DD)',
			'sexo':'Sexo',
			'persona': 'Adoptante',
			'vacuna':'Vacunas',
		}
		widgets={
			'nombre': forms.TextInput(attrs={'class':'form-control'}),
			'edad_aproximada': forms.TextInput(attrs={'class':'form-control'}),
			'fecha_rescate': forms.TextInput(attrs={'class':'form-control'}),
			'sexo':forms.TextInput(attrs={'class':'form-control'}),
			'persona': forms.Select(attrs={'class':'form-control'}),
			'vacuna':forms.CheckboxSelectMultiple(),
		}

apps/mascota/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse

from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.mascota.forms import MascotaForm
from apps.mascota.models import Mascota

# Create your views here.
def index(request):
	return render(request,'mascota/index.html')

def mascota_view(request):
	if request.method == 'POST': ##si me envian los datos por metodo post
		form = MascotaForm(request.POST)##renderizo el formulario
		if form.is_valid(): ##valido que se hallan recibido bien todos los campos
			form.save()##guardo el formulario
		return redirect("mascota:mascota_listar")##redirecciono a la vista principal
	else:##si me envian el formulario por metodo get
		form = MascotaForm()##renderizo el formulario
	return render(request,'mascota/mascota_form.html',{'form':form})

def mascota_list(request):
	mascota = Mascota.objects.all().order_by('id') ##hacer el queryset
	contexto = {'mascotas':mascota} ##creamos el contexto que contenga un diccionario,para mandarlo a la vista
	return render(request,'mascota/mascota_list.html',contexto)

def mascota_edit(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if (request.method == 'GET'):
		form = MascotaForm(instance=mascota)
	else:
		form = MascotaForm(request.POST, instance = mascota)
		if form.is_valid():
			form.save() 
		return redirect("mascota:mascota_listar")
	return render(request, "mascota/mascota_edit.html", {'form':form})

def mascota_delete(request, id_mascota):
	mascota = Mascota.objects.get(id=id_mascota)
	if request.method == 'POST':
		mascota.delete()
		return redirect("mascota:mascota_listar")
	return render(request, "mascota/mascota_delete.html", {'mascota':mascota})


class MascotaList(ListView):
	model = Mascota
	template_name = 'mascota/mascota_list.html'
		
class MascotaCreate(CreateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')

class MascotaUpdate(UpdateView):
	model = Mascota
	form_class = MascotaForm
	template_name = 'mascota/mascota_form.html'
	success_url = reverse_lazy('mascota:mascota_listar')
		
class MascotaDelete(DeleteView):
	model = Mascota
	template_name = 'mascota/mascota_delete.html'
	success_url = reverse_lazy('mascota:mascota_listar')

templates/mascota/index.html
{% extends 'base/base.html' %}

{% block tittle %}
	Plataforma
{% endblock %}
{% block titulo %}
	<h5>Bienvenido</h5>
{% endblock titulo %}

templates/mascota/mascota_delete.html
{% extends "base/base.html" %}

{% block tittle %}
	Mascota
{% endblock %}
{% block titulo %}
	<h5>Eliminar registro Mascota</h5>
{% endblock titulo %}
{% block content %}
	<div class="row">
		<div class="col s6 offset-s3">
			<h3>¿Desea eliminar el registro {{object.nombre}}?</h3>
			<form method="POST" style="text-align: center;">
				{% csrf_token %}
				<button class="btn waves-effect waves-light" type="submint">Sí, eliminar</button>
				<a class="btn waves-effect waves-light" href="{% url 'mascota:mascota_listar' %}">Cancelar</a>
			</form>	
		</div>
	</div>
{% endblock %}
{% block jsFiles %}
	<script type="text/javascript" src="{{STATIC_URL}}/static/js/mascotaform.js"></script>
{% endblock %}

templates/mascota/mascota_edit.html
{% extends "base/base.html" %}

{% block tittle %}
	Mascota
{% endblock %}
{% block titulo %}
	<h5>Editar una Mascota</h5>
{% endblock titulo %}
{% block content %}
	<div class="row">
		<div class="col s6 offset-s3">
			<form method="POST" >
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn waves-effect waves-light" type="submint">Guardar cambios</button>
				<button class="btn waves-effect waves-light" type="reset" >Limpiar</button>
				{{ form.errors }}
			</form>	
		</div>
	</div>
{% endblock %}
{% block jsFiles %}
	<script type="text/javascript" src="{{STATIC_URL}}/static/js/mascotaform.js"></script>
{% endblock %}

templates/mascota/mascota_form.html
{% extends "base/base.html" %}

{% block tittle %}
	Mascota
{% endblock %}
{% block titulo %}
{% endblock titulo %}
{% block content %}
	<div class="row">
		<div class="col s6 offset-s3">
			<form method="POST" >
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn waves-effect waves-light" type="submint">Guardar</button>
				<button class="btn waves-effect waves-light" type="reset" >Limpiar</button>
				{{ form.errors }}
			</form>	
		</div>
	</div>
{% endblock %}
{% block jsFiles %}
	<script type="text/javascript" src="{{STATIC_URL}}/static/js/mascotaform.js"></script>
{% endblock %}

templates/mascota/mascota_list.html
{% extends 'base/base.html' %}

{% block tittle %}
	Mascota
{% endblock %}
{% block titulo %}
	<h5>Lista de Mascotas</h5>
{% endblock titulo %}
{% block content %}
	<div class="row">
		<div class="col s8 offset-s2"> 
		  	<table class="bordered">
		    	<thead>
		          	<tr>
		            	<th>#</th>
			            <th>Nombre</th>
			            <th>Sexo</th>
			            <th>Edad</th>
			            <th>Fecha de Rescate</th>
			            <th>Adoptante</th>
			            <th>Acciones</th>
		          	</tr>
		        </thead>
		        <tbody>
		        {% if object_list %} 
		        	{%for mascota in object_list %}
		        	<tr>
			            <td>{{mascota.id}}</td>
			            <td>{{mascota.nombre}}</td>
			            <td>{{mascota.sexo}}</td>
			            <td>{{mascota.edad_aproximada}}</td>
			            <td>{{mascota.fecha_rescate}}</td>
			            <td>{{mascota.persona.nombre}} {{mascota.persona.apellido}}</td>
		          		<td>
		          			<a href="{% url 'mascota:mascota_editar' mascota.id %}" class="btn-floating waves-effect waves-light"><i class="material-icons left">mode_edit</i></a>
		          			<a href="{% url 'mascota:mascota_eliminar' mascota.id %}" class="btn-floating waves-effect waves-light"><i class="material-icons left">delete</i></a>
		          		</td>
		          	</tr>
		          	{% endfor%}
		      	{% else %}
		      		<h1>No se han creado registros</h1>
		      	{% endif %}
		        </tbody>
		  	</table>
	  	</div>
  	</div>
{% endblock %}